import type {
  SocialUser,
  PostWithAuthor,
  NotificationWithActor,
  ConversationWithParticipant,
  MarketplaceListingWithSeller,
} from '@/modules/domains/social/types';

/* =========================================================
   USERS
========================================================= */

export const ME: SocialUser = {
  userId: 'me',
  username: 'alex_builds',
  name: 'Alex Morgan',
  avatar: 'https://i.pravatar.cc/150?img=33',
  coverImage: 'https://picsum.photos/seed/cover-alex/800/200',
  bio: 'Full-stack developer · open source enthusiast · coffee addict ☕',
  location: 'Amsterdam, NL',
  website: 'https://alexbuilds.dev',
  followerCount: 3840,
  followingCount: 512,
  postCount: 164,
  isVerified: false,
  isFollowing: false,
  isFollowedBy: false,
};

export const USERS: SocialUser[] = [
  {
    userId: 'u-01',
    username: 'lena_design',
    name: 'Lena Fischer',
    avatar: 'https://i.pravatar.cc/150?img=47',
    coverImage: 'https://picsum.photos/seed/cover-lena/800/200',
    bio: 'Product designer & creative coder. Turning complex problems into simple, beautiful solutions ✨',
    location: 'Berlin, Germany',
    website: 'https://lena.design',
    followerCount: 12400,
    followingCount: 320,
    postCount: 284,
    isVerified: true,
    isFollowing: true,
    isFollowedBy: true,
  },
  {
    userId: 'u-02',
    username: 'marco_dev',
    name: 'Marco Rossi',
    avatar: 'https://i.pravatar.cc/150?img=11',
    bio: 'Backend engineer at @StartupXYZ. Loves Rust and loud mechanical keyboards.',
    location: 'Milan, Italy',
    followerCount: 1860,
    followingCount: 430,
    postCount: 92,
    isVerified: false,
    isFollowing: true,
    isFollowedBy: false,
  },
  {
    userId: 'u-03',
    username: 'sara_writes',
    name: 'Sara Kim',
    avatar: 'https://i.pravatar.cc/150?img=24',
    coverImage: 'https://picsum.photos/seed/cover-sara/800/200',
    bio: 'Technical writer & documentation nerd. Making APIs understandable since 2018.',
    location: 'Seoul, South Korea',
    website: 'https://sarawrites.io',
    followerCount: 5210,
    followingCount: 280,
    postCount: 341,
    isVerified: true,
    isFollowing: false,
    isFollowedBy: true,
  },
  {
    userId: 'u-04',
    username: 'devdiego',
    name: 'Diego Herrera',
    avatar: 'https://i.pravatar.cc/150?img=68',
    bio: 'CTO @ Stacklio · ex-Google · building the future of developer tooling',
    location: 'Buenos Aires, AR',
    followerCount: 28300,
    followingCount: 640,
    postCount: 512,
    isVerified: true,
    isFollowing: false,
    isFollowedBy: false,
  },
  {
    userId: 'u-05',
    username: 'pixel_cat',
    name: 'Nadia Volkov',
    avatar: 'https://i.pravatar.cc/150?img=54',
    bio: 'UI animator & motion designer. Making the web feel alive 🐱',
    location: 'Warsaw, Poland',
    followerCount: 7890,
    followingCount: 910,
    postCount: 203,
    isVerified: false,
    isFollowing: true,
    isFollowedBy: false,
  },
];

/* =========================================================
   POSTS / FEED
========================================================= */

export const FEED_POSTS: PostWithAuthor[] = [
  {
    postId: 'p-01',
    authorId: 'u-01',
    content: 'Just shipped a new open-source design system built with Tailwind CSS and React. Over 40 components, dark mode support, and full accessibility baked in. Check it out and leave a star if you like it! 🚀\n\n#OpenSource #DesignSystem #React',
    type: 'TEXT',
    status: 'PUBLISHED',
    privacy: 'PUBLIC',
    likeCount: 248,
    commentCount: 34,
    shareCount: 71,
    isLiked: true,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    author: USERS[0],
  },
  {
    postId: 'p-02',
    authorId: 'u-02',
    content: 'Morning vibes from the home office ☕',
    type: 'IMAGE',
    status: 'PUBLISHED',
    privacy: 'FRIENDS',
    mediaUrls: [
      'https://picsum.photos/seed/office1/600/400',
      'https://picsum.photos/seed/coffee1/600/400',
    ],
    likeCount: 92,
    commentCount: 8,
    shareCount: 3,
    isLiked: false,
    isBookmarked: true,
    createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000),
    author: USERS[1],
  },
  {
    postId: 'p-03',
    authorId: 'u-03',
    content: 'Hot take: the best documentation is the one that respects the reader\'s time. Stop burying the actual usage 6 scrolls deep. Put the example FIRST, explain after. You can thank me later.\n\n#TechWriting #DeveloperExperience #Docs',
    type: 'TEXT',
    status: 'PUBLISHED',
    privacy: 'PUBLIC',
    likeCount: 1340,
    commentCount: 187,
    shareCount: 412,
    isLiked: false,
    isBookmarked: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    author: USERS[2],
  },
  {
    postId: 'p-04',
    authorId: 'u-04',
    content: 'We just raised a $12M Series A to bring AI-powered developer tooling to every engineering team. Incredibly grateful to our investors, team, and early users who believed in this vision from day one. The best is yet to come. 🙏',
    type: 'TEXT',
    status: 'PUBLISHED',
    privacy: 'PUBLIC',
    likeCount: 5820,
    commentCount: 623,
    shareCount: 1840,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    author: USERS[3],
  },
  {
    postId: 'p-05',
    authorId: 'u-05',
    content: 'New motion design reel drop! 6 months of side projects — scroll transitions, page animations, and a few experiments with SVG morphing. All done in CSS and GSAP. No canvas, no WebGL 💅',
    type: 'IMAGE',
    status: 'PUBLISHED',
    privacy: 'PUBLIC',
    mediaUrls: [
      'https://picsum.photos/seed/motion1/600/400',
      'https://picsum.photos/seed/motion2/600/400',
      'https://picsum.photos/seed/motion3/600/400',
    ],
    likeCount: 3420,
    commentCount: 214,
    shareCount: 890,
    isLiked: true,
    isBookmarked: true,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    author: USERS[4],
  },
];

/* =========================================================
   NOTIFICATIONS
========================================================= */

export const NOTIFICATIONS: NotificationWithActor[] = [
  {
    notificationId: 'n-01',
    userId: 'me',
    type: 'LIKE',
    actorId: 'u-01',
    postId: 'p-01',
    message: 'liked your post about "building with Tailwind"',
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
    actor: USERS[0],
  },
  {
    notificationId: 'n-02',
    userId: 'me',
    type: 'COMMENT',
    actorId: 'u-03',
    postId: 'p-01',
    message: 'commented on your post: "This is fantastic! Can\'t wait to try it."',
    isRead: false,
    createdAt: new Date(Date.now() - 18 * 60 * 1000),
    actor: USERS[2],
  },
  {
    notificationId: 'n-03',
    userId: 'me',
    type: 'FOLLOW',
    actorId: 'u-04',
    message: 'started following you',
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    actor: USERS[3],
  },
  {
    notificationId: 'n-04',
    userId: 'me',
    type: 'MENTION',
    actorId: 'u-02',
    postId: 'p-05',
    message: 'mentioned you in a post',
    isRead: true,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    actor: USERS[1],
  },
  {
    notificationId: 'n-05',
    userId: 'me',
    type: 'SHARE',
    actorId: 'u-05',
    postId: 'p-03',
    message: 'shared your post',
    isRead: true,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    actor: USERS[4],
  },
  {
    notificationId: 'n-06',
    userId: 'me',
    type: 'LIKE',
    actorId: 'u-03',
    postId: 'p-01',
    message: 'and 42 others liked your post',
    isRead: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    actor: USERS[2],
  },
];

/* =========================================================
   CONVERSATIONS (MESSAGES)
========================================================= */

export const CONVERSATIONS: ConversationWithParticipant[] = [
  {
    conversationId: 'conv-01',
    participantIds: ['me', 'u-01'],
    lastMessage: 'Thanks! Let me know if you need any feedback on the component library.',
    lastMessageAt: new Date(Date.now() - 25 * 60 * 1000),
    unreadCount: 2,
    participant: USERS[0],
  },
  {
    conversationId: 'conv-02',
    participantIds: ['me', 'u-03'],
    lastMessage: 'Absolutely agree — examples first, always!',
    lastMessageAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    unreadCount: 0,
    participant: USERS[2],
  },
  {
    conversationId: 'conv-03',
    participantIds: ['me', 'u-02'],
    lastMessage: 'Did you try the new Rust async features?',
    lastMessageAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    unreadCount: 1,
    participant: USERS[1],
  },
  {
    conversationId: 'conv-04',
    participantIds: ['me', 'u-05'],
    lastMessage: 'That animation demo was insane btw 🔥',
    lastMessageAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    unreadCount: 0,
    participant: USERS[4],
  },
];

/* =========================================================
   MARKETPLACE LISTINGS
========================================================= */

export const MARKETPLACE_LISTINGS: MarketplaceListingWithSeller[] = [
  {
    listingId: 'l-01',
    sellerId: 'u-01',
    title: 'Herman Miller Aeron Chair – Size B',
    description: 'Barely used, great condition. Moving to a new city and can\'t take it with me. Original cost €1,400.',
    price: 650,
    currency: 'EUR',
    status: 'ACTIVE',
    condition: 'LIKE_NEW',
    category: 'Furniture',
    location: 'Berlin',
    imageUrls: ['https://picsum.photos/seed/chair1/400/400'],
    seller: USERS[0],
  },
  {
    listingId: 'l-02',
    sellerId: 'u-02',
    title: 'Pentax K1000 Vintage Film Camera',
    description: 'Works perfectly. Comes with 50mm f/2 lens. Great for beginners.',
    price: 89,
    currency: 'EUR',
    status: 'ACTIVE',
    condition: 'GOOD',
    category: 'Photography',
    location: 'Milan',
    imageUrls: ['https://picsum.photos/seed/camera1/400/400'],
    seller: USERS[1],
  },
  {
    listingId: 'l-03',
    sellerId: 'u-03',
    title: 'iPad Pro 12.9" M2 256GB + Apple Pencil',
    description: 'Selling because I switched to a drawing tablet. Perfect condition, still under warranty.',
    price: 820,
    currency: 'USD',
    status: 'ACTIVE',
    condition: 'LIKE_NEW',
    category: 'Electronics',
    location: 'Seoul',
    imageUrls: ['https://picsum.photos/seed/ipad1/400/400'],
    seller: USERS[2],
  },
  {
    listingId: 'l-04',
    sellerId: 'u-05',
    title: 'Wacom Cintiq 22 Drawing Tablet',
    description: 'Used for 2 years, works great. Upgrading to a larger model.',
    price: 420,
    currency: 'EUR',
    status: 'ACTIVE',
    condition: 'GOOD',
    category: 'Electronics',
    location: 'Warsaw',
    imageUrls: ['https://picsum.photos/seed/wacom1/400/400'],
    seller: USERS[4],
  },
  {
    listingId: 'l-05',
    sellerId: 'u-04',
    title: 'Standing Desk – UPLIFT V2 72" x 30"',
    description: 'Electric height-adjustable, 4 memory presets. Minor scratches on the surface.',
    price: 380,
    currency: 'USD',
    status: 'RESERVED',
    condition: 'FAIR',
    category: 'Furniture',
    location: 'Buenos Aires',
    imageUrls: ['https://picsum.photos/seed/desk1/400/400'],
    seller: USERS[3],
  },
  {
    listingId: 'l-06',
    sellerId: 'u-01',
    title: 'Design Books Bundle — 12 books',
    description: '"The Design of Everyday Things", "Don\'t Make Me Think", "Sprint", and 9 more classics.',
    price: 55,
    currency: 'EUR',
    status: 'ACTIVE',
    condition: 'GOOD',
    category: 'Books',
    location: 'Berlin',
    imageUrls: ['https://picsum.photos/seed/books1/400/400'],
    seller: USERS[0],
  },
];

/* =========================================================
   SUGGESTED USERS (for right sidebar)
========================================================= */

export const SUGGESTED_USERS: SocialUser[] = [USERS[2], USERS[3], USERS[4]];

/* =========================================================
   TRENDING TAGS (for right sidebar)
========================================================= */

export const TRENDING_TAGS = [
  { tag: 'OpenSource',         postCount: 48200 },
  { tag: 'TailwindCSS',        postCount: 32100 },
  { tag: 'TypeScript',         postCount: 29800 },
  { tag: 'DesignSystems',      postCount: 17400 },
  { tag: 'DeveloperExperience',postCount: 14200 },
];
