import { type ProductCardItem } from '@/modules/domain/ecommerce/ProductCard';
import { type CartItem } from '@/modules/domain/ecommerce/CartSummary';

export type Category = {
  id: string;
  label: string;
  slug: string;
  icon: string;
  count: number;
};

export type ProductSpecs = {
  ram?: string;
  gpu?: string;
  storage?: string;
  processor?: string;
  connectivity?: string;
  screenSize?: string;
  refreshRate?: string;
  resolution?: string;
  battery?: string;
  weight?: string;
  switchType?: string;
  driverSize?: string;
  outputPower?: string;
};

export const SPEC_FILTER_KEYS: { key: keyof ProductSpecs; label: string }[] = [
  { key: 'ram',          label: 'RAM' },
  { key: 'gpu',          label: 'GPU' },
  { key: 'storage',      label: 'Storage' },
  { key: 'processor',    label: 'Processor' },
  { key: 'connectivity', label: 'Connectivity' },
  { key: 'screenSize',   label: 'Screen Size' },
];

export type Product = ProductCardItem & {
  slug: string;
  category: string;
  description: string;
  features: string[];
  variants: {
    colors?: string[];
    sizes?: string[];
  };
  specs?: ProductSpecs;
  images: string[];
  sku: string;
  tags: string[];
};

export const CATEGORIES: Category[] = [
  { id: 'electronics', label: 'Electronics', slug: 'electronics', icon: '💻', count: 48 },
  { id: 'clothing',    label: 'Clothing',    slug: 'clothing',    icon: '👕', count: 136 },
  { id: 'home',        label: 'Home & Garden', slug: 'home',      icon: '🏡', count: 72 },
  { id: 'sports',      label: 'Sports',      slug: 'sports',      icon: '⚽', count: 55 },
  { id: 'books',       label: 'Books',       slug: 'books',       icon: '📚', count: 210 },
  { id: 'beauty',      label: 'Beauty',      slug: 'beauty',      icon: '✨', count: 89 },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    slug: 'wireless-noise-cancelling-headphones',
    name: 'Wireless Noise-Cancelling Headphones',
    brand: 'SoundWave',
    price: 149.99,
    originalPrice: 229.99,
    badge: 'Best Seller',
    badgeVariant: 'primary',
    rating: 4.7,
    reviewCount: 2341,
    inStock: true,
    category: 'electronics',
    description: 'Immerse yourself in sound with 40-hour battery life, adaptive ANC, and premium comfort. Perfect for travel, work, or everyday listening.',
    features: ['40-hour battery', 'Adaptive Active Noise Cancellation', 'Foldable design', 'Multipoint Bluetooth 5.3', 'Built-in voice assistant'],
    variants: { colors: ['Black', 'Silver', 'Midnight Blue'] },
    specs: { connectivity: 'Bluetooth 5.3', battery: '40 hours', driverSize: '40 mm' },
    images: [],
    sku: 'SW-HDP-001',
    tags: ['headphones', 'audio', 'wireless', 'anc'],
  },
  {
    id: 'p2',
    slug: 'slim-fit-cotton-crew-tee',
    name: 'Slim-Fit Cotton Crew T-Shirt',
    brand: 'UrbanThread',
    price: 29.99,
    originalPrice: 39.99,
    badge: 'New',
    badgeVariant: 'success',
    rating: 4.4,
    reviewCount: 874,
    inStock: true,
    category: 'clothing',
    description: 'Crafted from 100% organic cotton, this slim-fit tee offers all-day comfort without sacrificing style. A wardrobe essential in six versatile colours.',
    features: ['100% organic cotton', 'Pre-shrunk fabric', 'Reinforced stitching', 'Available in 6 colours', 'Machine washable'],
    variants: { sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'], colors: ['White', 'Black', 'Navy', 'Grey', 'Olive', 'Burgundy'] },
    images: [],
    sku: 'UT-TSH-002',
    tags: ['t-shirt', 'cotton', 'casual'],
  },
  {
    id: 'p3',
    slug: 'smart-coffee-maker',
    name: 'Smart Coffee Maker with App Control',
    brand: 'BrewMaster',
    price: 89.95,
    rating: 4.5,
    reviewCount: 612,
    inStock: true,
    category: 'home',
    description: 'Brew the perfect cup every time. Schedule, customise strength, and monitor your brew from your phone with the BrewMaster app.',
    features: ['App-controlled scheduling', '12-cup capacity', 'Keeps warm 2 hours', 'Built-in grinder option', 'Auto shut-off'],
    variants: {},
    images: [],
    sku: 'BM-CM-003',
    tags: ['coffee', 'smart home', 'kitchen'],
  },
  {
    id: 'p4',
    slug: 'ultra-boost-running-shoes',
    name: 'Ultra Boost Running Shoes',
    brand: 'StridePro',
    price: 119.99,
    originalPrice: 159.99,
    badge: 'Sale',
    badgeVariant: 'error',
    rating: 4.8,
    reviewCount: 3102,
    inStock: true,
    category: 'sports',
    description: 'Engineered for performance, these shoes feature responsive cushioning and breathable mesh to power every run, from 5K to marathon.',
    features: ['Responsive foam midsole', 'Breathable Primeknit upper', 'Continental rubber outsole', 'Reflective details', 'Lightweight 280g'],
    variants: { sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11', 'UK 12'], colors: ['Black/White', 'Grey/Red', 'Navy/Yellow'] },
    images: [],
    sku: 'SP-RSH-004',
    tags: ['running', 'shoes', 'sport'],
  },
  {
    id: 'p5',
    slug: 'mechanical-keyboard-rgb',
    name: 'Mechanical Keyboard — RGB Backlit',
    brand: 'KeyForge',
    price: 79.99,
    rating: 4.6,
    reviewCount: 1458,
    inStock: true,
    category: 'electronics',
    description: 'Tactile clicks, per-key RGB lighting and a compact 75% layout make this the ideal keyboard for coders and gamers alike.',
    features: ['Cherry MX-style switches', 'Per-key RGB', '75% compact layout', 'USB-C detachable cable', 'N-key rollover'],
    variants: { colors: ['Space Grey', 'White'] },
    specs: { connectivity: 'Wired (USB-C)', switchType: 'Mechanical (Cherry MX Blue)' },
    images: [],
    sku: 'KF-KBD-005',
    tags: ['keyboard', 'mechanical', 'rgb', 'gaming'],
  },
  {
    id: 'p6',
    slug: 'yoga-mat-premium',
    name: 'Premium Yoga Mat — Non-Slip 6mm',
    brand: 'ZenFlow',
    price: 44.99,
    originalPrice: 59.99,
    badge: '25% Off',
    badgeVariant: 'warning',
    rating: 4.9,
    reviewCount: 2780,
    inStock: true,
    category: 'sports',
    description: 'Extra-wide, non-slip surface with alignment lines. Eco-friendly TPE material, no latex, no PVC. Comes with a carry strap.',
    features: ['6mm cushioning', 'Non-slip both sides', 'Alignment guides printed', 'Eco-friendly TPE', 'Carry strap included'],
    variants: { colors: ['Purple', 'Teal', 'Coral', 'Black'] },
    images: [],
    sku: 'ZF-YMA-006',
    tags: ['yoga', 'fitness', 'mat'],
  },
  {
    id: 'p7',
    slug: 'scented-soy-candle-set',
    name: 'Scented Soy Candle Gift Set — 3 pack',
    brand: 'LuminHome',
    price: 34.99,
    rating: 4.7,
    reviewCount: 943,
    inStock: true,
    category: 'home',
    description: 'Hand-poured in small batches, these 100% soy wax candles come in three warming scents: Vanilla Oak, Amber Rose, and Cedarwood Sea.',
    features: ['100% natural soy wax', 'Cotton wick', 'Up to 45-hour burn each', 'Reusable glass jar', 'Gift-box packaging'],
    variants: {},
    images: [],
    sku: 'LH-CDL-007',
    tags: ['candles', 'home decor', 'gift'],
  },
  {
    id: 'p8',
    slug: 'portable-bluetooth-speaker',
    name: 'Portable Bluetooth Speaker — IP67 Waterproof',
    brand: 'SoundWave',
    price: 59.99,
    originalPrice: 79.99,
    badge: 'Top Rated',
    badgeVariant: 'info',
    rating: 4.5,
    reviewCount: 1876,
    inStock: true,
    category: 'electronics',
    description: 'Take the party anywhere. 360° sound, 24-hour playtime and military-grade waterproofing make this the ultimate outdoor speaker.',
    features: ['360° stereo sound', '24-hour battery', 'IP67 dust & water resistant', 'USB-C charging', 'True Wireless Stereo pairing'],
    variants: { colors: ['Black', 'Blue', 'Red', 'Green'] },
    specs: { connectivity: 'Bluetooth 5.0', battery: '24 hours', outputPower: '20 W' },
    images: [],
    sku: 'SW-SPK-008',
    tags: ['speaker', 'bluetooth', 'outdoor', 'waterproof'],
  },
  {
    id: 'p9',
    slug: 'skincare-starter-kit',
    name: 'Daily Glow Skincare Starter Kit',
    brand: 'GlowLab',
    price: 49.99,
    originalPrice: 69.99,
    badge: 'New',
    badgeVariant: 'success',
    rating: 4.6,
    reviewCount: 521,
    inStock: true,
    category: 'beauty',
    description: 'A complete morning and evening routine in one box. Cleanser, toner, serum, and moisturiser formulated for all skin types.',
    features: ['Fragrance-free formula', 'Dermatologist tested', 'Vegan & cruelty-free', '4-step system', '30-day supply'],
    variants: {},
    images: [],
    sku: 'GL-SKN-009',
    tags: ['skincare', 'beauty', 'routine'],
  },
  {
    id: 'p10',
    slug: 'atomic-habits-book',
    name: 'Atomic Habits — James Clear',
    brand: 'Penguin Books',
    price: 14.99,
    rating: 4.9,
    reviewCount: 18420,
    inStock: true,
    category: 'books',
    description: 'The life-changing million-copy #1 bestseller. Learn how tiny changes in behaviour can lead to remarkable results.',
    features: ['Paperback edition', '320 pages', 'International bestseller', 'Practical frameworks', 'Free companion guide'],
    variants: {},
    images: [],
    sku: 'PB-BK-010',
    tags: ['self-help', 'productivity', 'habits'],
  },
  {
    id: 'p11',
    slug: 'stainless-water-bottle',
    name: 'Insulated Stainless Steel Water Bottle — 1L',
    brand: 'HydroPeak',
    price: 27.99,
    rating: 4.8,
    reviewCount: 4200,
    inStock: true,
    category: 'sports',
    description: 'Keeps drinks cold 24 hours, hot 12 hours. Triple-wall vacuum insulation, BPA-free, leak-proof lid.',
    features: ['Triple-wall vacuum insulation', '24h cold / 12h hot', 'BPA-free', 'Leak-proof lid', 'Wide-mouth design'],
    variants: { colors: ['Matte Black', 'Arctic White', 'Forest Green', 'Copper'] },
    images: [],
    sku: 'HP-WBT-011',
    tags: ['water bottle', 'hydration', 'gym'],
  },
  {
    id: 'p12',
    slug: 'linen-duvet-cover',
    name: 'Pure Linen Duvet Cover — King',
    brand: 'CloudNest',
    price: 89.99,
    originalPrice: 119.99,
    badge: 'Sale',
    badgeVariant: 'error',
    rating: 4.6,
    reviewCount: 378,
    inStock: false,
    category: 'home',
    description: 'Stone-washed 100% European linen for the ultimate breathable, temperature-regulating sleep. Gets softer with every wash.',
    features: ['100% European linen', 'Stone-washed', 'Button closure', 'OEKO-TEX certified', 'Gets softer with washing'],
    variants: { colors: ['Natural', 'Dusty Pink', 'Sage', 'Slate Blue'] },
    images: [],
    sku: 'CN-BED-012',
    tags: ['bedding', 'linen', 'home'],
  },
  {
    id: 'p13',
    slug: 'gaming-laptop-rtx4060',
    name: 'ProGamer X15 — RTX 4060 Gaming Laptop',
    brand: 'NovaTech',
    price: 1249.99,
    originalPrice: 1499.99,
    badge: 'Best Seller',
    badgeVariant: 'primary',
    rating: 4.7,
    reviewCount: 892,
    inStock: true,
    category: 'electronics',
    description: 'Dominate every game with the RTX 4060, a 144 Hz display, and fast DDR5 RAM. Built for serious gamers who demand performance.',
    features: ['NVIDIA RTX 4060 8 GB', '16 GB DDR5 RAM', '512 GB NVMe SSD', '15.6" 144 Hz FHD display', 'RGB keyboard backlight', 'Wi-Fi 6E'],
    variants: { colors: ['Stealth Black', 'Storm Grey'] },
    specs: {
      ram: '16 GB DDR5',
      gpu: 'NVIDIA RTX 4060',
      storage: '512 GB NVMe SSD',
      processor: 'Intel Core i7-13700H',
      connectivity: 'Wi-Fi 6E / Bluetooth 5.3',
      screenSize: '15.6 inch',
      refreshRate: '144 Hz',
      weight: '2.1 kg',
    },
    images: [],
    sku: 'NT-LPT-013',
    tags: ['laptop', 'gaming', 'rtx', 'nvidia'],
  },
  {
    id: 'p14',
    slug: 'ultrabook-slim-14',
    name: 'AirSlim 14 Ultrabook — Intel Core i5',
    brand: 'NovaTech',
    price: 699.99,
    rating: 4.5,
    reviewCount: 534,
    inStock: true,
    category: 'electronics',
    description: 'Ultra-thin and feather-light at just 1.2 kg, the AirSlim 14 delivers all-day battery life and snappy performance for work and study.',
    features: ['Intel Core i5-1335U', '16 GB LPDDR5 RAM', '256 GB SSD', '14" IPS display 300 nits', '18-hour battery life', 'Thunderbolt 4'],
    variants: { colors: ['Silver', 'Space Blue'] },
    specs: {
      ram: '16 GB LPDDR5',
      gpu: 'Intel Iris Xe (Integrated)',
      storage: '256 GB SSD',
      processor: 'Intel Core i5-1335U',
      connectivity: 'Wi-Fi 6 / Bluetooth 5.2',
      screenSize: '14 inch',
      battery: '18 hours',
      weight: '1.2 kg',
    },
    images: [],
    sku: 'NT-LPT-014',
    tags: ['laptop', 'ultrabook', 'thin', 'portable'],
  },
  {
    id: 'p15',
    slug: 'gaming-laptop-rx7600',
    name: 'RyzenForce 16 — RX 7600M Gaming Laptop',
    brand: 'PulsePC',
    price: 979.99,
    originalPrice: 1149.99,
    badge: 'Sale',
    badgeVariant: 'error',
    rating: 4.6,
    reviewCount: 411,
    inStock: true,
    category: 'electronics',
    description: 'AMD power meets AMD graphics in this no-compromise 16-inch gaming laptop. Fluid 165 Hz panel, massive 1 TB storage, and 32 GB RAM.',
    features: ['AMD Radeon RX 7600M XT 8 GB', '32 GB DDR5 RAM', '1 TB NVMe SSD', '16" QHD 165 Hz display', 'MUX Switch', 'Wi-Fi 6E'],
    variants: { colors: ['Midnight Black'] },
    specs: {
      ram: '32 GB DDR5',
      gpu: 'AMD Radeon RX 7600M XT',
      storage: '1 TB NVMe SSD',
      processor: 'AMD Ryzen 7 7745HX',
      connectivity: 'Wi-Fi 6E / Bluetooth 5.3',
      screenSize: '16 inch',
      refreshRate: '165 Hz',
      weight: '2.4 kg',
    },
    images: [],
    sku: 'PP-LPT-015',
    tags: ['laptop', 'gaming', 'amd', 'ryzen'],
  },
  {
    id: 'p16',
    slug: 'workstation-laptop-32gb',
    name: 'WorkStation Pro 15 — Core i9 / 32 GB',
    brand: 'NovaTech',
    price: 1899.99,
    rating: 4.8,
    reviewCount: 278,
    inStock: true,
    category: 'electronics',
    description: 'Built for creators and engineers. The WorkStation Pro packs an i9 CPU, 32 GB RAM, and a colour-accurate 4K OLED display.',
    features: ['Intel Core i9-13900H', '32 GB DDR5 RAM', '1 TB NVMe SSD', '15.6" 4K OLED display', 'NVIDIA RTX 4070 8 GB', 'Thunderbolt 4 × 2'],
    variants: { colors: ['Platinum Silver'] },
    specs: {
      ram: '32 GB DDR5',
      gpu: 'NVIDIA RTX 4070',
      storage: '1 TB NVMe SSD',
      processor: 'Intel Core i9-13900H',
      connectivity: 'Wi-Fi 6E / Bluetooth 5.3',
      screenSize: '15.6 inch',
      refreshRate: '60 Hz (4K OLED)',
      weight: '2.0 kg',
    },
    images: [],
    sku: 'NT-LPT-016',
    tags: ['laptop', 'workstation', 'creator', 'oled'],
  },
  {
    id: 'p17',
    slug: 'budget-laptop-8gb',
    name: 'EduBook 14 — Student Laptop',
    brand: 'PulsePC',
    price: 399.99,
    badge: 'New',
    badgeVariant: 'success',
    rating: 4.2,
    reviewCount: 1023,
    inStock: true,
    category: 'electronics',
    description: 'An affordable, reliable laptop for students and everyday tasks. Full day battery, lightweight build, and the essentials done right.',
    features: ['AMD Ryzen 5 7520U', '8 GB LPDDR5 RAM', '256 GB SSD', '14" FHD IPS display', '12-hour battery', 'USB-C charging'],
    variants: { colors: ['Pebble Grey', 'Navy Blue'] },
    specs: {
      ram: '8 GB LPDDR5',
      gpu: 'AMD Radeon 610M (Integrated)',
      storage: '256 GB SSD',
      processor: 'AMD Ryzen 5 7520U',
      connectivity: 'Wi-Fi 5 / Bluetooth 5.0',
      screenSize: '14 inch',
      battery: '12 hours',
      weight: '1.5 kg',
    },
    images: [],
    sku: 'PP-LPT-017',
    tags: ['laptop', 'budget', 'student', 'amd'],
  },
];

export const FEATURED_PRODUCT_IDS = ['p1', 'p4', 'p6', 'p8', 'p2', 'p5'];
export const NEW_ARRIVALS_IDS = ['p9', 'p11', 'p7', 'p3'];

export const HERO_SLIDES = [
  {
    id: 'h1',
    headline: 'Summer Sale — Up to 40% Off',
    sub: "Shop the season's best deals on electronics, clothing, and more.",
    cta: 'Shop Now',
    ctaHref: '/theme/shop/products',
    badge: 'Limited time',
    accent: 'bg-primary',
  },
  {
    id: 'h2',
    headline: 'New Arrivals Just Dropped',
    sub: 'Fresh picks across beauty, sports, and home — be the first.',
    cta: 'Explore New',
    ctaHref: '/theme/shop/products',
    badge: 'New in',
    accent: 'bg-secondary',
  },
  {
    id: 'h3',
    headline: 'Free Shipping on Orders over $50',
    sub: 'No code needed. Fast & free delivery to your door.',
    cta: 'Start Shopping',
    ctaHref: '/theme/shop/products',
    badge: 'Free delivery',
    accent: 'bg-success',
  },
];

export const DEMO_CART_ITEMS: CartItem[] = [
  { id: 'p1', name: 'Wireless Noise-Cancelling Headphones', variant: 'Black', qty: 1, unitPrice: 149.99 },
  { id: 'p4', name: 'Ultra Boost Running Shoes', variant: 'UK 9 — Black/White', qty: 1, unitPrice: 119.99 },
  { id: 'p6', name: 'Premium Yoga Mat — Non-Slip 6mm', variant: 'Purple', qty: 2, unitPrice: 44.99 },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return PRODUCTS;
  return PRODUCTS.filter((p) => p.category === category);
}
