import type { Company, JobCategory, JobWithData } from '@/modules/domains/jobs/types';

export const COMPANIES: Company[] = [
  {
    companyId: 'c-01',
    name: 'Vercel',
    slug: 'vercel',
    description: 'Building tools that help developers ship fast. We power millions of frontend deployments worldwide.',
    logo: 'https://avatars.githubusercontent.com/u/14985020',
    website: 'https://vercel.com',
    industry: 'Developer Tools',
    size: '201–500',
    location: 'Remote',
    verified: true,
  },
  {
    companyId: 'c-02',
    name: 'Stripe',
    slug: 'stripe',
    description: 'A financial infrastructure platform for businesses of every size.',
    logo: 'https://avatars.githubusercontent.com/u/856813',
    website: 'https://stripe.com',
    industry: 'Fintech',
    size: '5001–10000',
    location: 'San Francisco, CA',
    verified: true,
  },
  {
    companyId: 'c-03',
    name: 'Linear',
    slug: 'linear',
    description: 'The issue tracking tool you will actually enjoy using. Linear helps teams streamline software projects.',
    logo: 'https://avatars.githubusercontent.com/u/60321695',
    website: 'https://linear.app',
    industry: 'SaaS',
    size: '51–200',
    location: 'Remote',
    verified: true,
  },
  {
    companyId: 'c-04',
    name: 'PlanetScale',
    slug: 'planetscale',
    description: 'The world\'s most advanced serverless MySQL platform.',
    logo: 'https://avatars.githubusercontent.com/u/52574936',
    website: 'https://planetscale.com',
    industry: 'Database / Cloud',
    size: '51–200',
    location: 'Remote',
    verified: false,
  },
  {
    companyId: 'c-05',
    name: 'Figma',
    slug: 'figma',
    description: 'Design, prototype, and gather feedback — all in one collaborative platform.',
    logo: 'https://avatars.githubusercontent.com/u/12503340',
    website: 'https://figma.com',
    industry: 'Design Tools',
    size: '1001–5000',
    location: 'San Francisco, CA',
    verified: true,
  },
];

export const JOB_CATEGORIES: JobCategory[] = [
  { categoryId: 'cat-01', title: 'Engineering',  slug: 'engineering',  description: 'Software & hardware engineering roles' },
  { categoryId: 'cat-02', title: 'Design',        slug: 'design',        description: 'UI, UX, and product design roles' },
  { categoryId: 'cat-03', title: 'Product',       slug: 'product',       description: 'Product management and strategy' },
  { categoryId: 'cat-04', title: 'Marketing',     slug: 'marketing',     description: 'Growth, content, and brand marketing' },
  { categoryId: 'cat-05', title: 'Sales',         slug: 'sales',         description: 'Account executives and sales development' },
  { categoryId: 'cat-06', title: 'Data',          slug: 'data',          description: 'Data science, analytics, and ML' },
];

export const JOBS: JobWithData[] = [
  {
    jobId: 'j-01',
    companyId: 'c-01',
    categoryId: 'cat-01',
    title: 'Senior Frontend Engineer',
    slug: 'senior-frontend-engineer-vercel',
    description: 'Join our core product team to build the next generation of our frontend platform. You will work on the developer experience that powers millions of deployments daily.',
    responsibilities: 'Design and implement new features for the Vercel dashboard. Collaborate with design and backend teams. Mentor junior engineers.',
    requirements: '5+ years of frontend experience. Deep knowledge of React and TypeScript. Experience with Next.js.',
    benefits: 'Fully remote, competitive salary, equity, health insurance, home office stipend.',
    type: 'FULL_TIME',
    workMode: 'REMOTE',
    experienceLevel: 'SENIOR',
    location: 'Remote (Worldwide)',
    country: 'US',
    salaryMin: 160000,
    salaryMax: 220000,
    currency: 'USD',
    salaryVisible: true,
    positions: 2,
    tags: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS'],
    status: 'PUBLISHED',
    applicationDeadline: new Date('2026-06-30'),
    views: 3412,
    applicationsCount: 128,
    publishedAt: new Date('2026-04-28'),
    company: { companyId: 'c-01', name: 'Vercel', slug: 'vercel', logo: 'https://avatars.githubusercontent.com/u/14985020', verified: true },
    category: { categoryId: 'cat-01', title: 'Engineering', slug: 'engineering' },
  },
  {
    jobId: 'j-02',
    companyId: 'c-02',
    categoryId: 'cat-01',
    title: 'Backend Engineer — Payments',
    slug: 'backend-engineer-payments-stripe',
    description: 'Help us build the financial infrastructure that powers millions of businesses. You will own critical payment processing flows serving global scale.',
    responsibilities: 'Build and scale payment processing systems. Improve reliability and latency of core APIs. Participate in on-call rotation.',
    requirements: '4+ years of backend engineering. Experience with distributed systems at scale. Proficiency in Go or Ruby.',
    benefits: 'Competitive salary, equity, 401k, health, dental, vision, catered lunches, and more.',
    type: 'FULL_TIME',
    workMode: 'HYBRID',
    experienceLevel: 'SENIOR',
    location: 'San Francisco, CA',
    country: 'US',
    salaryMin: 180000,
    salaryMax: 240000,
    currency: 'USD',
    salaryVisible: true,
    positions: 1,
    tags: ['Go', 'Distributed Systems', 'Payments', 'Ruby'],
    status: 'PUBLISHED',
    applicationDeadline: new Date('2026-07-15'),
    views: 5891,
    applicationsCount: 214,
    publishedAt: new Date('2026-05-01'),
    company: { companyId: 'c-02', name: 'Stripe', slug: 'stripe', logo: 'https://avatars.githubusercontent.com/u/856813', verified: true },
    category: { categoryId: 'cat-01', title: 'Engineering', slug: 'engineering' },
  },
  {
    jobId: 'j-03',
    companyId: 'c-03',
    categoryId: 'cat-02',
    title: 'Product Designer',
    slug: 'product-designer-linear',
    description: 'Shape the future of software project management. You will design elegant, powerful workflows that teams love to use every day.',
    responsibilities: 'Own end-to-end design for core product areas. Run user research sessions. Work closely with engineers during implementation.',
    requirements: '3+ years of product design. Strong systems thinking. Proficiency in Figma. Experience designing complex SaaS applications.',
    benefits: 'Remote-first, equity, flexible PTO, $3k equipment budget.',
    type: 'FULL_TIME',
    workMode: 'REMOTE',
    experienceLevel: 'MID',
    location: 'Remote (Americas / Europe)',
    country: null,
    salaryMin: 120000,
    salaryMax: 160000,
    currency: 'USD',
    salaryVisible: true,
    positions: 1,
    tags: ['Figma', 'UX Research', 'Design Systems', 'SaaS'],
    status: 'PUBLISHED',
    applicationDeadline: new Date('2026-06-20'),
    views: 2105,
    applicationsCount: 76,
    publishedAt: new Date('2026-05-03'),
    company: { companyId: 'c-03', name: 'Linear', slug: 'linear', logo: 'https://avatars.githubusercontent.com/u/60321695', verified: true },
    category: { categoryId: 'cat-02', title: 'Design', slug: 'design' },
  },
  {
    jobId: 'j-04',
    companyId: 'c-04',
    categoryId: 'cat-01',
    title: 'Database Reliability Engineer',
    slug: 'database-reliability-engineer-planetscale',
    description: 'Join us in solving some of the world\'s hardest database scalability challenges. You will keep PlanetScale\'s infrastructure running at peak reliability.',
    responsibilities: 'Manage Vitess clusters at scale. Develop internal tooling for database operations. Respond to incidents and perform post-mortems.',
    requirements: '3+ years managing MySQL or Vitess at scale. Strong understanding of database internals. Experience with Kubernetes.',
    benefits: 'Remote-first, competitive equity, health, 401k.',
    type: 'FULL_TIME',
    workMode: 'REMOTE',
    experienceLevel: 'SENIOR',
    location: 'Remote (US)',
    country: 'US',
    salaryMin: 150000,
    salaryMax: 200000,
    currency: 'USD',
    salaryVisible: true,
    positions: 1,
    tags: ['MySQL', 'Vitess', 'Kubernetes', 'Go', 'SRE'],
    status: 'PUBLISHED',
    applicationDeadline: null,
    views: 1342,
    applicationsCount: 38,
    publishedAt: new Date('2026-04-20'),
    company: { companyId: 'c-04', name: 'PlanetScale', slug: 'planetscale', logo: 'https://avatars.githubusercontent.com/u/52574936', verified: false },
    category: { categoryId: 'cat-01', title: 'Engineering', slug: 'engineering' },
  },
  {
    jobId: 'j-05',
    companyId: 'c-05',
    categoryId: 'cat-06',
    title: 'Data Scientist — Growth',
    slug: 'data-scientist-growth-figma',
    description: 'Use data to guide Figma\'s growth strategy. You will uncover how users experience the product and translate insights into measurable business impact.',
    responsibilities: 'Design and analyse A/B experiments. Build models to predict user activation and churn. Partner with marketing and product teams.',
    requirements: '3+ years in data science or analytics. Proficiency in Python and SQL. Experience with experimentation platforms.',
    benefits: 'Hybrid SF office, equity, generous benefits package.',
    type: 'FULL_TIME',
    workMode: 'HYBRID',
    experienceLevel: 'MID',
    location: 'San Francisco, CA',
    country: 'US',
    salaryMin: 145000,
    salaryMax: 185000,
    currency: 'USD',
    salaryVisible: true,
    positions: 2,
    tags: ['Python', 'SQL', 'A/B Testing', 'Analytics'],
    status: 'PUBLISHED',
    applicationDeadline: new Date('2026-06-30'),
    views: 1788,
    applicationsCount: 93,
    publishedAt: new Date('2026-05-05'),
    company: { companyId: 'c-05', name: 'Figma', slug: 'figma', logo: 'https://avatars.githubusercontent.com/u/12503340', verified: true },
    category: { categoryId: 'cat-06', title: 'Data', slug: 'data' },
  },
  {
    jobId: 'j-06',
    companyId: 'c-01',
    categoryId: 'cat-01',
    title: 'Infrastructure Engineer',
    slug: 'infrastructure-engineer-vercel',
    description: 'Build the edge infrastructure that powers global deployments in milliseconds. You will work at the intersection of networking, distributed systems, and developer experience.',
    responsibilities: 'Design and operate CDN and edge compute infrastructure. Improve build and deploy pipelines. Drive reliability and cost efficiency.',
    requirements: '5+ years in infrastructure or platform engineering. Experience with edge networks (Cloudflare, Fastly, etc.). Strong scripting skills.',
    benefits: 'Fully remote, equity, home office budget, unlimited PTO.',
    type: 'FULL_TIME',
    workMode: 'REMOTE',
    experienceLevel: 'LEAD',
    location: 'Remote (Worldwide)',
    country: null,
    salaryMin: 200000,
    salaryMax: 260000,
    currency: 'USD',
    salaryVisible: true,
    positions: 1,
    tags: ['CDN', 'Edge Compute', 'Rust', 'Networking'],
    status: 'PUBLISHED',
    applicationDeadline: new Date('2026-07-31'),
    views: 4210,
    applicationsCount: 162,
    publishedAt: new Date('2026-05-06'),
    company: { companyId: 'c-01', name: 'Vercel', slug: 'vercel', logo: 'https://avatars.githubusercontent.com/u/14985020', verified: true },
    category: { categoryId: 'cat-01', title: 'Engineering', slug: 'engineering' },
  },
  {
    jobId: 'j-07',
    companyId: 'c-03',
    categoryId: 'cat-03',
    title: 'Product Manager — Core',
    slug: 'product-manager-core-linear',
    description: 'Drive the vision and roadmap for Linear\'s core issue tracking experience. You will work with a world-class team to make software project management feel effortless.',
    responsibilities: 'Own product roadmap for core tracking features. Synthesize customer feedback into priorities. Partner with design and engineering.',
    requirements: '4+ years in product management. Experience with developer tools or SaaS. Strong written communication.',
    benefits: 'Remote-first, equity, flexible PTO.',
    type: 'FULL_TIME',
    workMode: 'REMOTE',
    experienceLevel: 'SENIOR',
    location: 'Remote (Americas)',
    country: null,
    salaryMin: 140000,
    salaryMax: 190000,
    currency: 'USD',
    salaryVisible: false,
    positions: 1,
    tags: ['Product Management', 'SaaS', 'Developer Tools'],
    status: 'PUBLISHED',
    applicationDeadline: null,
    views: 889,
    applicationsCount: 44,
    publishedAt: new Date('2026-05-07'),
    company: { companyId: 'c-03', name: 'Linear', slug: 'linear', logo: 'https://avatars.githubusercontent.com/u/60321695', verified: true },
    category: { categoryId: 'cat-03', title: 'Product', slug: 'product' },
  },
  {
    jobId: 'j-08',
    companyId: 'c-02',
    categoryId: 'cat-04',
    title: 'Developer Marketing Manager',
    slug: 'developer-marketing-manager-stripe',
    description: 'Tell the story of Stripe to the world\'s developers. You will create content, run events, and develop campaigns that resonate with technical audiences.',
    responsibilities: 'Plan and execute developer-focused content strategy. Partner with DevRel and product marketing. Measure campaign effectiveness.',
    requirements: '3+ years in developer marketing or content marketing. Comfortable working with technical topics. Strong analytical mindset.',
    benefits: 'Hybrid SF office, equity, comprehensive benefits.',
    type: 'FULL_TIME',
    workMode: 'HYBRID',
    experienceLevel: 'MID',
    location: 'San Francisco, CA',
    country: 'US',
    salaryMin: 115000,
    salaryMax: 155000,
    currency: 'USD',
    salaryVisible: true,
    positions: 1,
    tags: ['Developer Marketing', 'Content Strategy', 'Analytics'],
    status: 'PUBLISHED',
    applicationDeadline: new Date('2026-06-15'),
    views: 672,
    applicationsCount: 31,
    publishedAt: new Date('2026-05-04'),
    company: { companyId: 'c-02', name: 'Stripe', slug: 'stripe', logo: 'https://avatars.githubusercontent.com/u/856813', verified: true },
    category: { categoryId: 'cat-04', title: 'Marketing', slug: 'marketing' },
  },
];

export const FEATURED_JOB = JOBS[0];
